### ISSUE TITLE
Issues with latest version of Go lang (go1.14.4)

### ISSUE THREAD

**Issue by tanujsoni9** [pgpool/pgpool2_exporter#1]
I am having issues with the latest version of go in build process.

![](https://user-images.githubusercontent.com/65275338/85516867-4ddead80-b61c-11ea-91d8-d7d2e2dd1095.png)
This can be resolved by running `go mod vendor`. 
With Go version 1.13.12, It ran without any issues. Please add the support to latest version Go lang.

**Comment by pengbo0328** [comment]
Fixed in ver. [1.0.0](https://github.com/pgpool/pgpool2_exporter/releases/tag/v1.0.0).
