### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by n-oden** [pgpool/pgpool2_exporter#15]
Hey @pengbo0328 -- there have been a bunch of changes landed since the 1.1.0 release last October.  Would it be possible to cut a 1.2.0 release at this point?  I have a couple of downstream builds that I'd like to point to a stable post-1.1 version of the exporter.

**Comment by pengbo0328** [comment]
@n-oden Yes. I have released [v1.2.0](https://github.com/pgpool/pgpool2_exporter/releases/tag/v1.2.0).

**Comment by n-oden** [comment]
Thank you!
