### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by matejhasul** [pgpool/pgpool2_exporter#18]
By any chance, do you have any grafana dashboard for pgpool exported metrics. Something like mentioned in https://b-peng.blogspot.com/2020/10/pgpool2-exporter.html. Cannot find anything usable on the web.

**Comment by smatvienko-tb** [comment]
Hey, @matejhasul!
I found the dashboard for Pgpool2 at [Grafana](https://grafana.com/grafana/dashboards/?search=pgpool) searching for [pgpool] (https://grafana.com/grafana/dashboards/15805) dashboard.
You can try to import it by ID `15805`
![image](https://user-images.githubusercontent.com/79898499/181182718-c754c019-ba07-451d-a278-26684b736b9e.png)

If you failed to import by ID, then download the dashboard and try to import from JSON.

For my [ThingsBoard](https://thingsboard.io/) cluster, it looks like this on the screenshot below (cut). 
![image](https://user-images.githubusercontent.com/79898499/181182104-3f06596f-15a2-4965-a6bf-55b25793bd70.png)

**Comment by pengbo0328** [comment]
@matejhasul 
Sorry for the late response.
You can find the dashboard [here](https://github.com/pgpool/pgpool2_exporter/blob/master/dashboards/pgpool2.json).

**Comment by matejhasul** [comment]
Thank you!
