### ISSUE TITLE
Do not exit if pgpool is not reachable on startup

### ISSUE THREAD

**Issue by AnirudhGoel** [pgpool/pgpool2_exporter#20]
Currently on startup, if the exporter cannot connect to pgpool it throws an error and exits. This is okay if the pgpool connection parameters are incorrect but if the parameters are correct and pgpool is down, the exporter should just print the metric `up = 0` and wait for pgpool to be back up and not exit with an error.
This behaviour causes an issue if the exporter is run as a sidecar container with pgpool and pgpool is waiting for searching a primary (`search_primary_node_timeout = 0`) for a few minutes. Then, after ~30 seconds, the exporter not being able to find the pgpool exits with an error and because one of the sidecar container is down, the orchestrator kills the whole job to restart it.

**Comment by AnirudhGoel** [comment]
I patched this problem in my local installation by replacing the following snippet in `pgpool2_exporter.go`:

```go
if err != nil {
    level.Error(Logger).Log("err", err)
    os.Exit(1)
}
```

With this:
```go
for err != nil {
    level.Error(Logger).Log("err", err)
    level.Info(Logger).Log("info", "sleeping for 5 seconds before trying to connect again")
    time.Sleep(5 * time.Second)

    db, err = getDBConn(dsn)
}
```

Let me know if I can make a MR with this patch. :)

**Comment by pengbo0328** [comment]
@AnirudhGoel Sorry for the late reply.
Yes. You are correct. I have tested your patch and it works well.
Could you create a Pull request?

**Comment by BlondGhost** [comment]
Thank you @pengbo0328 for testing. Yes I will create a patch.

**Comment by AnirudhGoel** [comment]
Thank you @pengbo0328 for the test. Yes, I am creating a PR.

**Comment by AnirudhGoel** [comment]
https://github.com/pgpool/pgpool2_exporter/pull/26

Here it is.

**Comment by pengbo0328** [comment]
Thank you! @AnirudhGoel 
I have merged your pull request.
