### ISSUE TITLE
Make error on Debian 11 with Go 

### ISSUE THREAD

**Issue by viswn** [pgpool/pgpool2_exporter#30]
Hi,

I am getting an error when I try to build pgpool2_exporter on Debian 11.

Any help or ideas would be very much appreciated.

root@vbox0:/opt/pgpool2_exporter# go version
go version go1.20.6 linux/amd64

root@vbox0:/opt/pgpool2_exporter# make
>> building binaries
 >   pgpool2_exporter
# github.com/pgpool/pgpool2_exporter
./pgpool2_exporter.go:31:2: "os" imported and not used
!! command failed: build -o /opt/pgpool2_exporter/pgpool2_exporter -ldflags -X github.com/prometheus/common/version.Version=1.2.1 -X github.com/prometheus/common/version.Revision=c76acd4012c52869f11c3fffd7ab626e2d0144b5 -X github.com/prometheus/common/version.Branch=master -X github.com/prometheus/common/version.BuildUser=root@vbox0 -X github.com/prometheus/common/version.BuildDate=20230712-05:24:19  -extldflags '-static' -a -tags 'netgo static_build' github.com/pgpool/pgpool2_exporter/cmd/pgpool2_exporter: exit status 1
make: *** [Makefile:17: build] Error 1

Thanks and Regards

**Comment by cihadkba** [comment]
Hi @pengbo0328,

I'm using rhel and getting the same error. Can you provide a solution on the issue?

Thanks.

**Comment by viswn** [comment]
I used the current release https://github.com/pgpool/pgpool2_exporter/releases/tag/v1.2.1 instead of trying to compile.

Works fine.

**Comment by cihadkba** [comment]
for those who have the problem. Open the pgpool2_exporter.go file. Deleting the "os" parameter in import worked for me.

![image](https://github.com/pgpool/pgpool2_exporter/assets/23129390/6f6e2289-9274-4a74-8362-3def1509eedb)

**Comment by dr1nf3rn0** [comment]
Fixed in pull request https://github.com/pgpool/pgpool2_exporter/pull/33
