### ISSUE TITLE
Release v1.2.2 docker image

### ISSUE THREAD

**Issue by KennyChenFight** [pgpool/pgpool2_exporter#36]
Hi @pengbo0328, would you release v1.2.2 docker image which contains this [feature](https://github.com/pgpool/pgpool2_exporter/commit/979dfb6ee7675344fa6fed47d9f6b377f45a1121)
Many thx.

**Comment by DorBreger** [comment]
Highly needed!

**Comment by KennyChenFight** [comment]
Hi @pengbo0328 Can you help with that 🙏

**Comment by pengbo0328** [comment]
@DorBreger @KennyChenFight Sorry for the late response.
I am going to release v1.2.2 docker image this month.

**Comment by pengbo0328** [comment]
@DorBreger @KennyChenFight
Now v1.2.2 docker image is available.
Sorry for the inconvenience.

**Comment by KennyChenFight** [comment]
> @DorBreger @KennyChenFight Now v1.2.2 docker image is available. Sorry for the inconvenience.

Thank you very much ❤️
