### ISSUE TITLE
Not working when running via Systemd service

### ISSUE THREAD

**Issue by ernitishkumar** [pgpool/pgpool2_exporter#39]
Environment variables are not available either from .bashrc file
or from dedicated environment variable file
when running the executable file via Systemd service.

Anyway to provide environment variable via external environment file placed in /etc/defaut/pgpoo2_exporter
and available in systemd unit ?

**Comment by dr1nf3rn0** [comment]
You can place environment variables to **/etc/sysconfig/pgpool**
```
OPTS=" -D -n"
STOP_OPTS="-m smart"

PATH=/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
then pass that file path to **EnvironmentFile** in your systemd unit file:

```
[Unit]
Description=Pgpool-II
After=syslog.target network.target

[Service]

User=postgres
Group=postgres

EnvironmentFile=-/etc/sysconfig/pgpool

ExecStart=/usr/bin/pgpool -f /etc/pgpool-II/pgpool.conf $OPTS
ExecStop=/usr/bin/pgpool -f /etc/pgpool-II/pgpool.conf $STOP_OPTS stop
ExecReload=/usr/bin/pgpool -f /etc/pgpool-II/pgpool.conf reload

Restart=on-failure
[Install]
WantedBy=multi-user.target
```

**$OPTS** and **$STOP_OPTS** will be available

**Comment by ernitishkumar** [comment]
I think -f flag is not supported by pgpool2_exporter yet !

The solution you suggested is for running pgpool as a systemd service.

I am facing issue with running PgPool2_Exporter as a systemd service.

**Comment by dr1nf3rn0** [comment]
You can try this:

__/etc/sysconfig/pgpool2-exporter__

```
DATA_SOURCE_USER="pgpool"
DATA_SOURCE_PASS="pgpool"
DATA_SOURCE_URI="localhost:9999/postgres?sslmode=disable"
```

__/etc/systemd/system/pgpool2-exporter.service__
```
[Unit]
Description=Pgpool-II Prometheus exporter
After=syslog.target network.target pgpool.service
BindsTo=pgpool.service

[Service]
Type=simple
User=postgres
Group=postgres

EnvironmentFile=-/etc/sysconfig/pgpool2-exporter

ExecStart=/usr/bin/pgpool2_exporter --web.listen-address="your_hostname:9719" --web.telemetry-path="/metrics" --log.level="info" --log.format="logfmt"
ExecStop=/bin/kill -15 $MAINPID
Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target
```

**Comment by ernitishkumar** [comment]
Thanks that worked with some modification !
