### ISSUE TITLE
Request to make the exporter a golang package

### ISSUE THREAD

**Issue by oba11** [pgpool/pgpool2_exporter#4]
Thanks for the really good pgpool exporter 👏 .

We would like to integrate exporter into an existing pgpool wrapper but this is not possible because the current implementation is a `main` package. Is it possible to refactor the codebase for the exporter functionality to be re-usable as a package?

Thank you again 🥇

**Comment by pengbo0328** [comment]
Thank you!

We would appreciate it if you could create a pull request.

**Comment by n-oden** [comment]
@oba11 take a look at #12 and see if it works for you? It's very much the minimum viable change version of this and could probably stand some further refactoring.
