### ISSUE TITLE
Latest version requires pgpool >= v4.2

### ISSUE THREAD

**Issue by reoops** [pgpool/pgpool2_exporter#6]
README.md  states that pgpool >= v3.6 is required. Seems to require pgpool >= v4.2. 

After building and starting I got back following error message (and yes I access pgpool2 not postgresql directly):

```sh
pgpool --version
pgpool-II version 4.1.4 (karasukiboshi)

DATA_SOURCE_NAME="postgresql://user:passs@host/postgres?sslmode=disable" ./pgpool2_exporter 
INFO[0000] Error running query on database:  pool_backend_stats pq: unrecognized configuration parameter "pool_backend_stats"  source="pgpool2_exporter.go:451"
INFO[0000] Error running query on database:  pool_health_check_stats pq: unrecognized configuration parameter "pool_health_check_stats"  source="pgpool2_exporter.go:451"
FATA[0000] map[pool_backend_stats:Error running query on database:  pool_backend_stats pq: unrecognized configuration parameter "pool_backend_stats"
 pool_health_check_stats:Error running query on database:  pool_health_check_stats pq: unrecognized configuration parameter "pool_health_check_stats"
]  source="pgpool2_exporter.go:543"
```

Here the workaround for older versions:
```sh
git checkout d1a6e457a8abbdd62b8601e59d9180b8a00e10bb
go mod tidy
go mod vendor
make
```

Please detect version or at least update the README.

**Comment by pengbo0328** [comment]
Thank you for reporting this issue.

I am going to fix this issue to support old versions (e.g. 4.1.x).

**Comment by pengbo0328** [comment]
I have fixed this issue.
Now Pgpool-II exporter is able to detect Pgpool-II version. 

[commit](https://github.com/pgpool/pgpool2_exporter/commit/1d7883b98e99173103922191a3c9ad078a092077)

**Comment by reoops** [comment]
Thank you very much. Works like a charm.
