### ISSUE TITLE
DockerFile does not have an environment variable to pass in PGPOOL DB NAME

### ISSUE THREAD

**Issue by pratik-pagade** [pgpool/pgpool2_exporter#8]
The docker file does not contain an environment variable for the DB. It's using the default 'postgres' db in the data source. Can you please add in the environment variable to the dockerfile so that it can be overriden.

**Comment by pengbo0328** [comment]
I have added a new environment variable "POSTGRES_DATABASE" to override the database name. 
https://github.com/pgpool/pgpool2_exporter/commit/a4c7d803b17f78ef7cc170135c7bcb51c3ef6cde

**Comment by pratik-pagade** [comment]
Could you also push this updated dockerimage build to the pgpool dockerhub repository ? Since I'm using a macOS the compiled binaries don't work, when I do a docker run, so having the updated docker image will be very helpful. Thank you @pengbo0328.

**Comment by pengbo0328** [comment]
I have released it as a new version 1.1.0.
You can find the updated docker images [here](https://hub.docker.com/r/pgpool/pgpool2_exporter).

**Comment by pratik-pagade** [comment]
Thank you!
